### ISSUE TITLE
[1.12.2] Flat Lamp missing inverted variant and doesn't function

### ISSUE THREAD

**Issue by DeadSix27** [TehNut/Xtones#12]
When the flat lamp is powered it doesn't provide any light, just the block texture changes.

**Comment by saphsara** [comment]
we having same issue

**Comment by TehNut** [comment]
Light seems to work just fine for me. 

![](https://i.imgur.com/mfThANA.png)

**Comment by TehNut** [comment]
Alright, some useful information would have been that this is only happening on servers.

**Comment by saphsara** [comment]
Sorry I forgot about single player

**Comment by saphsara** [comment]
Sorry didn't realize. I forgot about single player


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Nick Ignoffo <notifications@github.com> Date: 11/20/17  7:25 PM  (GMT-05:00) To: TehNut/Xtones <Xtones@noreply.github.com> Cc: saphsara <saphandra@yahoo.com>, Comment <comment@noreply.github.com> Subject: Re: [TehNut/Xtones] [1.12.2] Flat Lamp missing inverted variant and doesn't function (#12) 
Alright, some useful information would have been that this is only happening on servers.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TehNut/Xtones","title":"TehNut/Xtones","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TehNut/Xtones"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TehNut in #12: Alright, some useful information would have been that this is only happening on servers."}],"action":{"name":"View Issue","url":"https://github.com/TehNut/Xtones/issues/12#issuecomment-345875950"}}}

**Comment by saphsara** [comment]
thank you for working on this.. Is it for 1.12.1 or 1.12.2 . i am running 1.12.2 . update says 1.12.1

**Comment by DeadSix27** [comment]
@saphsara probably works  fine on 1.12.2, most mods are inter compatible between 1.12 | 1.12.1 | 1.12.2

**Comment by saphsara** [comment]
Yes it does I took the chance and tried it. Thanks for working on this. Keep up the great work. 
null
